### ISSUE TITLE
Axios proxy request

### ISSUE THREAD

**Issue by Dam998** [PipedreamHQ/docs#33]
Hi,
I read your article "Use an HTTP proxy to proxy requests through another host", this works very well so thank you
but it's not work with proxy ipv6, works only with ipv4. Do you know why? Thank you so much

**Comment by dylburger** [comment]
HI @Dam998 , I'm not sure, and it might help to have some specific information on the error you're encountering. It's possible it's an issue in the `https-proxy-agent` library. 

Either way, would you mind emailing support@pipedream.com with information on the error you're seeing and I can dig in more?
